/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AzureTestRouteImport } from './routes/azure-test'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthDebugRouteImport } from './routes/auth/debug'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthAzureCallbackRouteImport } from './routes/auth/azure-callback'
import { Route as AuthenticatedSyncStatusRouteImport } from './routes/_authenticated/sync-status'
import { Route as AuthenticatedRichTextDemoRouteImport } from './routes/_authenticated/rich-text-demo'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedProductivityRouteImport } from './routes/_authenticated/productivity'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMonitoringRouteImport } from './routes/_authenticated/monitoring'
import { Route as AuthenticatedMarginAnalysisRouteImport } from './routes/_authenticated/margin-analysis'
import { Route as AuthenticatedEditorTestRouteImport } from './routes/_authenticated/editor-test'
import { Route as AuthenticatedEditableDemoRouteImport } from './routes/_authenticated/editable-demo'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBusinessIntelligenceRouteImport } from './routes/_authenticated/business-intelligence'
import { Route as AuthenticatedAzureStatusRouteImport } from './routes/_authenticated/azure-status'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedFormsRouteRouteImport } from './routes/_authenticated/forms/route'
import { Route as AuthenticatedVendorsIndexRouteImport } from './routes/_authenticated/vendors/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedRfpManagementIndexRouteImport } from './routes/_authenticated/rfp-management/index'
import { Route as AuthenticatedRfpGptIndexRouteImport } from './routes/_authenticated/rfp-gpt/index'
import { Route as AuthenticatedRedlineReportIndexRouteImport } from './routes/_authenticated/redline-report/index'
import { Route as AuthenticatedQuotesIndexRouteImport } from './routes/_authenticated/quotes/index'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders/index'
import { Route as AuthenticatedMyApprovalsIndexRouteImport } from './routes/_authenticated/my-approvals/index'
import { Route as AuthenticatedMarginAnalysisIndexRouteImport } from './routes/_authenticated/margin-analysis/index'
import { Route as AuthenticatedInvoicesIndexRouteImport } from './routes/_authenticated/invoices/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedGapReportIndexRouteImport } from './routes/_authenticated/gap-report/index'
import { Route as AuthenticatedForecastIndexRouteImport } from './routes/_authenticated/forecast/index'
import { Route as AuthenticatedDailyWinsIndexRouteImport } from './routes/_authenticated/daily-wins/index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedApprovalsIndexRouteImport } from './routes/_authenticated/approvals/index'
import { Route as AuthenticatedAiMarginAnalysisIndexRouteImport } from './routes/_authenticated/ai-margin-analysis/index'
import { Route as AuthenticatedVendorsVendor_idRouteImport } from './routes/_authenticated/vendors/$vendor_id'
import { Route as AuthenticatedVendorsVendorIdRouteImport } from './routes/_authenticated/vendors/$vendorId'
import { Route as AuthenticatedSettingsUserManagementRouteImport } from './routes/_authenticated/settings/user-management'
import { Route as AuthenticatedSettingsTeamManagementRouteImport } from './routes/_authenticated/settings/team-management'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsGoalsManagementRouteImport } from './routes/_authenticated/settings/goals-management'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedSettingsProfileIndexRouteImport } from './routes/_authenticated/settings/profile/index'
import { Route as AuthenticatedFormsPublishedIndexRouteImport } from './routes/_authenticated/forms/published/index'
import { Route as AuthenticatedFormsBuilderIndexRouteImport } from './routes/_authenticated/forms/builder/index'
import { Route as AuthenticatedFormsPublishedChar91formIdChar93RouteImport } from './routes/_authenticated/forms/published/[formId]'
import { Route as AuthenticatedCustomersCustomerNoAnalysisRouteImport } from './routes/_authenticated/customers/$customerNo.analysis'

const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AzureTestRoute = AzureTestRouteImport.update({
  id: '/azure-test',
  path: '/azure-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthDebugRoute = AuthDebugRouteImport.update({
  id: '/auth/debug',
  path: '/auth/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAzureCallbackRoute = AuthAzureCallbackRouteImport.update({
  id: '/auth/azure-callback',
  path: '/auth/azure-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSyncStatusRoute = AuthenticatedSyncStatusRouteImport.update({
  id: '/sync-status',
  path: '/sync-status',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRichTextDemoRoute =
  AuthenticatedRichTextDemoRouteImport.update({
    id: '/rich-text-demo',
    path: '/rich-text-demo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductivityRoute =
  AuthenticatedProductivityRouteImport.update({
    id: '/productivity',
    path: '/productivity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonitoringRoute = AuthenticatedMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarginAnalysisRoute =
  AuthenticatedMarginAnalysisRouteImport.update({
    id: '/margin-analysis',
    path: '/margin-analysis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEditorTestRoute = AuthenticatedEditorTestRouteImport.update({
  id: '/editor-test',
  path: '/editor-test',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEditableDemoRoute =
  AuthenticatedEditableDemoRouteImport.update({
    id: '/editable-demo',
    path: '/editable-demo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBusinessIntelligenceRoute =
  AuthenticatedBusinessIntelligenceRouteImport.update({
    id: '/business-intelligence',
    path: '/business-intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAzureStatusRoute =
  AuthenticatedAzureStatusRouteImport.update({
    id: '/azure-status',
    path: '/azure-status',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFormsRouteRoute = AuthenticatedFormsRouteRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendorsIndexRoute =
  AuthenticatedVendorsIndexRouteImport.update({
    id: '/vendors/',
    path: '/vendors/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedRfpManagementIndexRoute =
  AuthenticatedRfpManagementIndexRouteImport.update({
    id: '/rfp-management/',
    path: '/rfp-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRfpGptIndexRoute =
  AuthenticatedRfpGptIndexRouteImport.update({
    id: '/rfp-gpt/',
    path: '/rfp-gpt/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRedlineReportIndexRoute =
  AuthenticatedRedlineReportIndexRouteImport.update({
    id: '/redline-report/',
    path: '/redline-report/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuotesIndexRoute =
  AuthenticatedQuotesIndexRouteImport.update({
    id: '/quotes/',
    path: '/quotes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyApprovalsIndexRoute =
  AuthenticatedMyApprovalsIndexRouteImport.update({
    id: '/my-approvals/',
    path: '/my-approvals/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarginAnalysisIndexRoute =
  AuthenticatedMarginAnalysisIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMarginAnalysisRoute,
  } as any)
const AuthenticatedInvoicesIndexRoute =
  AuthenticatedInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGapReportIndexRoute =
  AuthenticatedGapReportIndexRouteImport.update({
    id: '/gap-report/',
    path: '/gap-report/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedForecastIndexRoute =
  AuthenticatedForecastIndexRouteImport.update({
    id: '/forecast/',
    path: '/forecast/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDailyWinsIndexRoute =
  AuthenticatedDailyWinsIndexRouteImport.update({
    id: '/daily-wins/',
    path: '/daily-wins/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApprovalsIndexRoute =
  AuthenticatedApprovalsIndexRouteImport.update({
    id: '/approvals/',
    path: '/approvals/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiMarginAnalysisIndexRoute =
  AuthenticatedAiMarginAnalysisIndexRouteImport.update({
    id: '/ai-margin-analysis/',
    path: '/ai-margin-analysis/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorsVendor_idRoute =
  AuthenticatedVendorsVendor_idRouteImport.update({
    id: '/vendors/$vendor_id',
    path: '/vendors/$vendor_id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorsVendorIdRoute =
  AuthenticatedVendorsVendorIdRouteImport.update({
    id: '/vendors/$vendorId',
    path: '/vendors/$vendorId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsUserManagementRoute =
  AuthenticatedSettingsUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsTeamManagementRoute =
  AuthenticatedSettingsTeamManagementRouteImport.update({
    id: '/team-management',
    path: '/team-management',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsGoalsManagementRoute =
  AuthenticatedSettingsGoalsManagementRouteImport.update({
    id: '/goals-management',
    path: '/goals-management',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsProfileIndexRoute =
  AuthenticatedSettingsProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedFormsPublishedIndexRoute =
  AuthenticatedFormsPublishedIndexRouteImport.update({
    id: '/published/',
    path: '/published/',
    getParentRoute: () => AuthenticatedFormsRouteRoute,
  } as any)
const AuthenticatedFormsBuilderIndexRoute =
  AuthenticatedFormsBuilderIndexRouteImport.update({
    id: '/builder/',
    path: '/builder/',
    getParentRoute: () => AuthenticatedFormsRouteRoute,
  } as any)
const AuthenticatedFormsPublishedChar91formIdChar93Route =
  AuthenticatedFormsPublishedChar91formIdChar93RouteImport.update({
    id: '/published/[formId]',
    path: '/published/[formId]',
    getParentRoute: () => AuthenticatedFormsRouteRoute,
  } as any)
const AuthenticatedCustomersCustomerNoAnalysisRoute =
  AuthenticatedCustomersCustomerNoAnalysisRouteImport.update({
    id: '/customers/$customerNo/analysis',
    path: '/customers/$customerNo/analysis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteRouteWithChildren
  '/azure-test': typeof AzureTestRoute
  '/chat': typeof ChatRoute
  '/forms': typeof AuthenticatedFormsRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/azure-status': typeof AuthenticatedAzureStatusRoute
  '/business-intelligence': typeof AuthenticatedBusinessIntelligenceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/editable-demo': typeof AuthenticatedEditableDemoRoute
  '/editor-test': typeof AuthenticatedEditorTestRoute
  '/margin-analysis': typeof AuthenticatedMarginAnalysisRouteWithChildren
  '/monitoring': typeof AuthenticatedMonitoringRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/productivity': typeof AuthenticatedProductivityRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/rich-text-demo': typeof AuthenticatedRichTextDemoRoute
  '/sync-status': typeof AuthenticatedSyncStatusRoute
  '/auth/azure-callback': typeof AuthAzureCallbackRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/debug': typeof AuthDebugRoute
  '/': typeof AuthenticatedIndexRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/goals-management': typeof AuthenticatedSettingsGoalsManagementRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/team-management': typeof AuthenticatedSettingsTeamManagementRoute
  '/settings/user-management': typeof AuthenticatedSettingsUserManagementRoute
  '/vendors/$vendorId': typeof AuthenticatedVendorsVendorIdRoute
  '/vendors/$vendor_id': typeof AuthenticatedVendorsVendor_idRoute
  '/ai-margin-analysis': typeof AuthenticatedAiMarginAnalysisIndexRoute
  '/approvals': typeof AuthenticatedApprovalsIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/daily-wins': typeof AuthenticatedDailyWinsIndexRoute
  '/forecast': typeof AuthenticatedForecastIndexRoute
  '/gap-report': typeof AuthenticatedGapReportIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/margin-analysis/': typeof AuthenticatedMarginAnalysisIndexRoute
  '/my-approvals': typeof AuthenticatedMyApprovalsIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/quotes': typeof AuthenticatedQuotesIndexRoute
  '/redline-report': typeof AuthenticatedRedlineReportIndexRoute
  '/rfp-gpt': typeof AuthenticatedRfpGptIndexRoute
  '/rfp-management': typeof AuthenticatedRfpManagementIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/vendors': typeof AuthenticatedVendorsIndexRoute
  '/customers/$customerNo/analysis': typeof AuthenticatedCustomersCustomerNoAnalysisRoute
  '/forms/published/[formId]': typeof AuthenticatedFormsPublishedChar91formIdChar93Route
  '/forms/builder': typeof AuthenticatedFormsBuilderIndexRoute
  '/forms/published': typeof AuthenticatedFormsPublishedIndexRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileIndexRoute
}
export interface FileRoutesByTo {
  '/azure-test': typeof AzureTestRoute
  '/chat': typeof ChatRoute
  '/forms': typeof AuthenticatedFormsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/azure-status': typeof AuthenticatedAzureStatusRoute
  '/business-intelligence': typeof AuthenticatedBusinessIntelligenceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/editable-demo': typeof AuthenticatedEditableDemoRoute
  '/editor-test': typeof AuthenticatedEditorTestRoute
  '/monitoring': typeof AuthenticatedMonitoringRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/productivity': typeof AuthenticatedProductivityRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/rich-text-demo': typeof AuthenticatedRichTextDemoRoute
  '/sync-status': typeof AuthenticatedSyncStatusRoute
  '/auth/azure-callback': typeof AuthAzureCallbackRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/debug': typeof AuthDebugRoute
  '/': typeof AuthenticatedIndexRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/goals-management': typeof AuthenticatedSettingsGoalsManagementRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/team-management': typeof AuthenticatedSettingsTeamManagementRoute
  '/settings/user-management': typeof AuthenticatedSettingsUserManagementRoute
  '/vendors/$vendorId': typeof AuthenticatedVendorsVendorIdRoute
  '/vendors/$vendor_id': typeof AuthenticatedVendorsVendor_idRoute
  '/ai-margin-analysis': typeof AuthenticatedAiMarginAnalysisIndexRoute
  '/approvals': typeof AuthenticatedApprovalsIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/daily-wins': typeof AuthenticatedDailyWinsIndexRoute
  '/forecast': typeof AuthenticatedForecastIndexRoute
  '/gap-report': typeof AuthenticatedGapReportIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/margin-analysis': typeof AuthenticatedMarginAnalysisIndexRoute
  '/my-approvals': typeof AuthenticatedMyApprovalsIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/quotes': typeof AuthenticatedQuotesIndexRoute
  '/redline-report': typeof AuthenticatedRedlineReportIndexRoute
  '/rfp-gpt': typeof AuthenticatedRfpGptIndexRoute
  '/rfp-management': typeof AuthenticatedRfpManagementIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/vendors': typeof AuthenticatedVendorsIndexRoute
  '/customers/$customerNo/analysis': typeof AuthenticatedCustomersCustomerNoAnalysisRoute
  '/forms/published/[formId]': typeof AuthenticatedFormsPublishedChar91formIdChar93Route
  '/forms/builder': typeof AuthenticatedFormsBuilderIndexRoute
  '/forms/published': typeof AuthenticatedFormsPublishedIndexRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/azure-test': typeof AzureTestRoute
  '/chat': typeof ChatRoute
  '/_authenticated/forms': typeof AuthenticatedFormsRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/azure-status': typeof AuthenticatedAzureStatusRoute
  '/_authenticated/business-intelligence': typeof AuthenticatedBusinessIntelligenceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/editable-demo': typeof AuthenticatedEditableDemoRoute
  '/_authenticated/editor-test': typeof AuthenticatedEditorTestRoute
  '/_authenticated/margin-analysis': typeof AuthenticatedMarginAnalysisRouteWithChildren
  '/_authenticated/monitoring': typeof AuthenticatedMonitoringRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/productivity': typeof AuthenticatedProductivityRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/rich-text-demo': typeof AuthenticatedRichTextDemoRoute
  '/_authenticated/sync-status': typeof AuthenticatedSyncStatusRoute
  '/auth/azure-callback': typeof AuthAzureCallbackRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/debug': typeof AuthDebugRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/goals-management': typeof AuthenticatedSettingsGoalsManagementRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/team-management': typeof AuthenticatedSettingsTeamManagementRoute
  '/_authenticated/settings/user-management': typeof AuthenticatedSettingsUserManagementRoute
  '/_authenticated/vendors/$vendorId': typeof AuthenticatedVendorsVendorIdRoute
  '/_authenticated/vendors/$vendor_id': typeof AuthenticatedVendorsVendor_idRoute
  '/_authenticated/ai-margin-analysis/': typeof AuthenticatedAiMarginAnalysisIndexRoute
  '/_authenticated/approvals/': typeof AuthenticatedApprovalsIndexRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/daily-wins/': typeof AuthenticatedDailyWinsIndexRoute
  '/_authenticated/forecast/': typeof AuthenticatedForecastIndexRoute
  '/_authenticated/gap-report/': typeof AuthenticatedGapReportIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/_authenticated/margin-analysis/': typeof AuthenticatedMarginAnalysisIndexRoute
  '/_authenticated/my-approvals/': typeof AuthenticatedMyApprovalsIndexRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/_authenticated/quotes/': typeof AuthenticatedQuotesIndexRoute
  '/_authenticated/redline-report/': typeof AuthenticatedRedlineReportIndexRoute
  '/_authenticated/rfp-gpt/': typeof AuthenticatedRfpGptIndexRoute
  '/_authenticated/rfp-management/': typeof AuthenticatedRfpManagementIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/vendors/': typeof AuthenticatedVendorsIndexRoute
  '/_authenticated/customers/$customerNo/analysis': typeof AuthenticatedCustomersCustomerNoAnalysisRoute
  '/_authenticated/forms/published/[formId]': typeof AuthenticatedFormsPublishedChar91formIdChar93Route
  '/_authenticated/forms/builder/': typeof AuthenticatedFormsBuilderIndexRoute
  '/_authenticated/forms/published/': typeof AuthenticatedFormsPublishedIndexRoute
  '/_authenticated/settings/profile/': typeof AuthenticatedSettingsProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/azure-test'
    | '/chat'
    | '/forms'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/azure-status'
    | '/business-intelligence'
    | '/dashboard'
    | '/editable-demo'
    | '/editor-test'
    | '/margin-analysis'
    | '/monitoring'
    | '/notifications'
    | '/productivity'
    | '/profile'
    | '/rich-text-demo'
    | '/sync-status'
    | '/auth/azure-callback'
    | '/auth/callback'
    | '/auth/debug'
    | '/'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/goals-management'
    | '/settings/notifications'
    | '/settings/team-management'
    | '/settings/user-management'
    | '/vendors/$vendorId'
    | '/vendors/$vendor_id'
    | '/ai-margin-analysis'
    | '/approvals'
    | '/apps'
    | '/chats'
    | '/customers'
    | '/daily-wins'
    | '/forecast'
    | '/gap-report'
    | '/help-center'
    | '/invoices'
    | '/margin-analysis/'
    | '/my-approvals'
    | '/orders'
    | '/quotes'
    | '/redline-report'
    | '/rfp-gpt'
    | '/rfp-management'
    | '/settings/'
    | '/tasks'
    | '/users'
    | '/vendors'
    | '/customers/$customerNo/analysis'
    | '/forms/published/[formId]'
    | '/forms/builder'
    | '/forms/published'
    | '/settings/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/azure-test'
    | '/chat'
    | '/forms'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/azure-status'
    | '/business-intelligence'
    | '/dashboard'
    | '/editable-demo'
    | '/editor-test'
    | '/monitoring'
    | '/notifications'
    | '/productivity'
    | '/profile'
    | '/rich-text-demo'
    | '/sync-status'
    | '/auth/azure-callback'
    | '/auth/callback'
    | '/auth/debug'
    | '/'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/goals-management'
    | '/settings/notifications'
    | '/settings/team-management'
    | '/settings/user-management'
    | '/vendors/$vendorId'
    | '/vendors/$vendor_id'
    | '/ai-margin-analysis'
    | '/approvals'
    | '/apps'
    | '/chats'
    | '/customers'
    | '/daily-wins'
    | '/forecast'
    | '/gap-report'
    | '/help-center'
    | '/invoices'
    | '/margin-analysis'
    | '/my-approvals'
    | '/orders'
    | '/quotes'
    | '/redline-report'
    | '/rfp-gpt'
    | '/rfp-management'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/vendors'
    | '/customers/$customerNo/analysis'
    | '/forms/published/[formId]'
    | '/forms/builder'
    | '/forms/published'
    | '/settings/profile'
  id:
    | '__root__'
    | '/_authenticated'
    | '/azure-test'
    | '/chat'
    | '/_authenticated/forms'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/azure-status'
    | '/_authenticated/business-intelligence'
    | '/_authenticated/dashboard'
    | '/_authenticated/editable-demo'
    | '/_authenticated/editor-test'
    | '/_authenticated/margin-analysis'
    | '/_authenticated/monitoring'
    | '/_authenticated/notifications'
    | '/_authenticated/productivity'
    | '/_authenticated/profile'
    | '/_authenticated/rich-text-demo'
    | '/_authenticated/sync-status'
    | '/auth/azure-callback'
    | '/auth/callback'
    | '/auth/debug'
    | '/_authenticated/'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/goals-management'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/team-management'
    | '/_authenticated/settings/user-management'
    | '/_authenticated/vendors/$vendorId'
    | '/_authenticated/vendors/$vendor_id'
    | '/_authenticated/ai-margin-analysis/'
    | '/_authenticated/approvals/'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/customers/'
    | '/_authenticated/daily-wins/'
    | '/_authenticated/forecast/'
    | '/_authenticated/gap-report/'
    | '/_authenticated/help-center/'
    | '/_authenticated/invoices/'
    | '/_authenticated/margin-analysis/'
    | '/_authenticated/my-approvals/'
    | '/_authenticated/orders/'
    | '/_authenticated/quotes/'
    | '/_authenticated/redline-report/'
    | '/_authenticated/rfp-gpt/'
    | '/_authenticated/rfp-management/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/vendors/'
    | '/_authenticated/customers/$customerNo/analysis'
    | '/_authenticated/forms/published/[formId]'
    | '/_authenticated/forms/builder/'
    | '/_authenticated/forms/published/'
    | '/_authenticated/settings/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AzureTestRoute: typeof AzureTestRoute
  ChatRoute: typeof ChatRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  AuthAzureCallbackRoute: typeof AuthAzureCallbackRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthDebugRoute: typeof AuthDebugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/azure-test': {
      id: '/azure-test'
      path: '/azure-test'
      fullPath: '/azure-test'
      preLoaderRoute: typeof AzureTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/debug': {
      id: '/auth/debug'
      path: '/auth/debug'
      fullPath: '/auth/debug'
      preLoaderRoute: typeof AuthDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/azure-callback': {
      id: '/auth/azure-callback'
      path: '/auth/azure-callback'
      fullPath: '/auth/azure-callback'
      preLoaderRoute: typeof AuthAzureCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sync-status': {
      id: '/_authenticated/sync-status'
      path: '/sync-status'
      fullPath: '/sync-status'
      preLoaderRoute: typeof AuthenticatedSyncStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rich-text-demo': {
      id: '/_authenticated/rich-text-demo'
      path: '/rich-text-demo'
      fullPath: '/rich-text-demo'
      preLoaderRoute: typeof AuthenticatedRichTextDemoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/productivity': {
      id: '/_authenticated/productivity'
      path: '/productivity'
      fullPath: '/productivity'
      preLoaderRoute: typeof AuthenticatedProductivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitoring': {
      id: '/_authenticated/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AuthenticatedMonitoringRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/margin-analysis': {
      id: '/_authenticated/margin-analysis'
      path: '/margin-analysis'
      fullPath: '/margin-analysis'
      preLoaderRoute: typeof AuthenticatedMarginAnalysisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/editor-test': {
      id: '/_authenticated/editor-test'
      path: '/editor-test'
      fullPath: '/editor-test'
      preLoaderRoute: typeof AuthenticatedEditorTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/editable-demo': {
      id: '/_authenticated/editable-demo'
      path: '/editable-demo'
      fullPath: '/editable-demo'
      preLoaderRoute: typeof AuthenticatedEditableDemoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business-intelligence': {
      id: '/_authenticated/business-intelligence'
      path: '/business-intelligence'
      fullPath: '/business-intelligence'
      preLoaderRoute: typeof AuthenticatedBusinessIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/azure-status': {
      id: '/_authenticated/azure-status'
      path: '/azure-status'
      fullPath: '/azure-status'
      preLoaderRoute: typeof AuthenticatedAzureStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forms': {
      id: '/_authenticated/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof AuthenticatedFormsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendors/': {
      id: '/_authenticated/vendors/'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AuthenticatedVendorsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/rfp-management/': {
      id: '/_authenticated/rfp-management/'
      path: '/rfp-management'
      fullPath: '/rfp-management'
      preLoaderRoute: typeof AuthenticatedRfpManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rfp-gpt/': {
      id: '/_authenticated/rfp-gpt/'
      path: '/rfp-gpt'
      fullPath: '/rfp-gpt'
      preLoaderRoute: typeof AuthenticatedRfpGptIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/redline-report/': {
      id: '/_authenticated/redline-report/'
      path: '/redline-report'
      fullPath: '/redline-report'
      preLoaderRoute: typeof AuthenticatedRedlineReportIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotes/': {
      id: '/_authenticated/quotes/'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof AuthenticatedQuotesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-approvals/': {
      id: '/_authenticated/my-approvals/'
      path: '/my-approvals'
      fullPath: '/my-approvals'
      preLoaderRoute: typeof AuthenticatedMyApprovalsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/margin-analysis/': {
      id: '/_authenticated/margin-analysis/'
      path: '/'
      fullPath: '/margin-analysis/'
      preLoaderRoute: typeof AuthenticatedMarginAnalysisIndexRouteImport
      parentRoute: typeof AuthenticatedMarginAnalysisRoute
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gap-report/': {
      id: '/_authenticated/gap-report/'
      path: '/gap-report'
      fullPath: '/gap-report'
      preLoaderRoute: typeof AuthenticatedGapReportIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forecast/': {
      id: '/_authenticated/forecast/'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof AuthenticatedForecastIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/daily-wins/': {
      id: '/_authenticated/daily-wins/'
      path: '/daily-wins'
      fullPath: '/daily-wins'
      preLoaderRoute: typeof AuthenticatedDailyWinsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approvals/': {
      id: '/_authenticated/approvals/'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-margin-analysis/': {
      id: '/_authenticated/ai-margin-analysis/'
      path: '/ai-margin-analysis'
      fullPath: '/ai-margin-analysis'
      preLoaderRoute: typeof AuthenticatedAiMarginAnalysisIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendors/$vendor_id': {
      id: '/_authenticated/vendors/$vendor_id'
      path: '/vendors/$vendor_id'
      fullPath: '/vendors/$vendor_id'
      preLoaderRoute: typeof AuthenticatedVendorsVendor_idRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendors/$vendorId': {
      id: '/_authenticated/vendors/$vendorId'
      path: '/vendors/$vendorId'
      fullPath: '/vendors/$vendorId'
      preLoaderRoute: typeof AuthenticatedVendorsVendorIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/user-management': {
      id: '/_authenticated/settings/user-management'
      path: '/user-management'
      fullPath: '/settings/user-management'
      preLoaderRoute: typeof AuthenticatedSettingsUserManagementRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/team-management': {
      id: '/_authenticated/settings/team-management'
      path: '/team-management'
      fullPath: '/settings/team-management'
      preLoaderRoute: typeof AuthenticatedSettingsTeamManagementRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/goals-management': {
      id: '/_authenticated/settings/goals-management'
      path: '/goals-management'
      fullPath: '/settings/goals-management'
      preLoaderRoute: typeof AuthenticatedSettingsGoalsManagementRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/profile/': {
      id: '/_authenticated/settings/profile/'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/forms/published/': {
      id: '/_authenticated/forms/published/'
      path: '/published'
      fullPath: '/forms/published'
      preLoaderRoute: typeof AuthenticatedFormsPublishedIndexRouteImport
      parentRoute: typeof AuthenticatedFormsRouteRoute
    }
    '/_authenticated/forms/builder/': {
      id: '/_authenticated/forms/builder/'
      path: '/builder'
      fullPath: '/forms/builder'
      preLoaderRoute: typeof AuthenticatedFormsBuilderIndexRouteImport
      parentRoute: typeof AuthenticatedFormsRouteRoute
    }
    '/_authenticated/forms/published/[formId]': {
      id: '/_authenticated/forms/published/[formId]'
      path: '/published/[formId]'
      fullPath: '/forms/published/[formId]'
      preLoaderRoute: typeof AuthenticatedFormsPublishedChar91formIdChar93RouteImport
      parentRoute: typeof AuthenticatedFormsRouteRoute
    }
    '/_authenticated/customers/$customerNo/analysis': {
      id: '/_authenticated/customers/$customerNo/analysis'
      path: '/customers/$customerNo/analysis'
      fullPath: '/customers/$customerNo/analysis'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerNoAnalysisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedFormsRouteRouteChildren {
  AuthenticatedFormsPublishedChar91formIdChar93Route: typeof AuthenticatedFormsPublishedChar91formIdChar93Route
  AuthenticatedFormsBuilderIndexRoute: typeof AuthenticatedFormsBuilderIndexRoute
  AuthenticatedFormsPublishedIndexRoute: typeof AuthenticatedFormsPublishedIndexRoute
}

const AuthenticatedFormsRouteRouteChildren: AuthenticatedFormsRouteRouteChildren =
  {
    AuthenticatedFormsPublishedChar91formIdChar93Route:
      AuthenticatedFormsPublishedChar91formIdChar93Route,
    AuthenticatedFormsBuilderIndexRoute: AuthenticatedFormsBuilderIndexRoute,
    AuthenticatedFormsPublishedIndexRoute:
      AuthenticatedFormsPublishedIndexRoute,
  }

const AuthenticatedFormsRouteRouteWithChildren =
  AuthenticatedFormsRouteRoute._addFileChildren(
    AuthenticatedFormsRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsGoalsManagementRoute: typeof AuthenticatedSettingsGoalsManagementRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsTeamManagementRoute: typeof AuthenticatedSettingsTeamManagementRoute
  AuthenticatedSettingsUserManagementRoute: typeof AuthenticatedSettingsUserManagementRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSettingsProfileIndexRoute: typeof AuthenticatedSettingsProfileIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsGoalsManagementRoute:
      AuthenticatedSettingsGoalsManagementRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsTeamManagementRoute:
      AuthenticatedSettingsTeamManagementRoute,
    AuthenticatedSettingsUserManagementRoute:
      AuthenticatedSettingsUserManagementRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
    AuthenticatedSettingsProfileIndexRoute:
      AuthenticatedSettingsProfileIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedMarginAnalysisRouteChildren {
  AuthenticatedMarginAnalysisIndexRoute: typeof AuthenticatedMarginAnalysisIndexRoute
}

const AuthenticatedMarginAnalysisRouteChildren: AuthenticatedMarginAnalysisRouteChildren =
  {
    AuthenticatedMarginAnalysisIndexRoute:
      AuthenticatedMarginAnalysisIndexRoute,
  }

const AuthenticatedMarginAnalysisRouteWithChildren =
  AuthenticatedMarginAnalysisRoute._addFileChildren(
    AuthenticatedMarginAnalysisRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFormsRouteRoute: typeof AuthenticatedFormsRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedAzureStatusRoute: typeof AuthenticatedAzureStatusRoute
  AuthenticatedBusinessIntelligenceRoute: typeof AuthenticatedBusinessIntelligenceRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEditableDemoRoute: typeof AuthenticatedEditableDemoRoute
  AuthenticatedEditorTestRoute: typeof AuthenticatedEditorTestRoute
  AuthenticatedMarginAnalysisRoute: typeof AuthenticatedMarginAnalysisRouteWithChildren
  AuthenticatedMonitoringRoute: typeof AuthenticatedMonitoringRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProductivityRoute: typeof AuthenticatedProductivityRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRichTextDemoRoute: typeof AuthenticatedRichTextDemoRoute
  AuthenticatedSyncStatusRoute: typeof AuthenticatedSyncStatusRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedVendorsVendorIdRoute: typeof AuthenticatedVendorsVendorIdRoute
  AuthenticatedVendorsVendor_idRoute: typeof AuthenticatedVendorsVendor_idRoute
  AuthenticatedAiMarginAnalysisIndexRoute: typeof AuthenticatedAiMarginAnalysisIndexRoute
  AuthenticatedApprovalsIndexRoute: typeof AuthenticatedApprovalsIndexRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedDailyWinsIndexRoute: typeof AuthenticatedDailyWinsIndexRoute
  AuthenticatedForecastIndexRoute: typeof AuthenticatedForecastIndexRoute
  AuthenticatedGapReportIndexRoute: typeof AuthenticatedGapReportIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
  AuthenticatedMyApprovalsIndexRoute: typeof AuthenticatedMyApprovalsIndexRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
  AuthenticatedQuotesIndexRoute: typeof AuthenticatedQuotesIndexRoute
  AuthenticatedRedlineReportIndexRoute: typeof AuthenticatedRedlineReportIndexRoute
  AuthenticatedRfpGptIndexRoute: typeof AuthenticatedRfpGptIndexRoute
  AuthenticatedRfpManagementIndexRoute: typeof AuthenticatedRfpManagementIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedVendorsIndexRoute: typeof AuthenticatedVendorsIndexRoute
  AuthenticatedCustomersCustomerNoAnalysisRoute: typeof AuthenticatedCustomersCustomerNoAnalysisRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFormsRouteRoute: AuthenticatedFormsRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedAzureStatusRoute: AuthenticatedAzureStatusRoute,
  AuthenticatedBusinessIntelligenceRoute:
    AuthenticatedBusinessIntelligenceRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEditableDemoRoute: AuthenticatedEditableDemoRoute,
  AuthenticatedEditorTestRoute: AuthenticatedEditorTestRoute,
  AuthenticatedMarginAnalysisRoute:
    AuthenticatedMarginAnalysisRouteWithChildren,
  AuthenticatedMonitoringRoute: AuthenticatedMonitoringRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProductivityRoute: AuthenticatedProductivityRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRichTextDemoRoute: AuthenticatedRichTextDemoRoute,
  AuthenticatedSyncStatusRoute: AuthenticatedSyncStatusRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedVendorsVendorIdRoute: AuthenticatedVendorsVendorIdRoute,
  AuthenticatedVendorsVendor_idRoute: AuthenticatedVendorsVendor_idRoute,
  AuthenticatedAiMarginAnalysisIndexRoute:
    AuthenticatedAiMarginAnalysisIndexRoute,
  AuthenticatedApprovalsIndexRoute: AuthenticatedApprovalsIndexRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedDailyWinsIndexRoute: AuthenticatedDailyWinsIndexRoute,
  AuthenticatedForecastIndexRoute: AuthenticatedForecastIndexRoute,
  AuthenticatedGapReportIndexRoute: AuthenticatedGapReportIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
  AuthenticatedMyApprovalsIndexRoute: AuthenticatedMyApprovalsIndexRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
  AuthenticatedQuotesIndexRoute: AuthenticatedQuotesIndexRoute,
  AuthenticatedRedlineReportIndexRoute: AuthenticatedRedlineReportIndexRoute,
  AuthenticatedRfpGptIndexRoute: AuthenticatedRfpGptIndexRoute,
  AuthenticatedRfpManagementIndexRoute: AuthenticatedRfpManagementIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedVendorsIndexRoute: AuthenticatedVendorsIndexRoute,
  AuthenticatedCustomersCustomerNoAnalysisRoute:
    AuthenticatedCustomersCustomerNoAnalysisRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AzureTestRoute: AzureTestRoute,
  ChatRoute: ChatRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  AuthAzureCallbackRoute: AuthAzureCallbackRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthDebugRoute: AuthDebugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
